#!/usr/bin/env python3
# Launch opponent_predictor with venv activated (same pattern as run_mpc_controller.bash)
import sys
from multi_purpose_mpc_ros.opponent_predictor import main

if __name__ == '__main__':
    sys.exit(main())
